"""
Django settings for VAD_Journey project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'Aplicaciones/FrontEnd/static/js', 'serviceworker.js')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_u7d(jjmsy0n79)@v0d)n#w^odr@_*eenkj4agmn8nq5=ewt2%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['vadjourney.pythonanywhere.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps locales
    'Aplicaciones.FrontEnd',
    'Aplicaciones.users',
    # PWA
    'pwa',
    # Google recaptcha
    'captcha',
    # Import or export to/from file to Django ORM
    'import_export',
    # 3 parties authentication
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET=True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VAD_Journey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

WSGI_APPLICATION = 'VAD_Journey.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'VAD_Journey',
        'USER':'postgres',
        'PASSWORD':'SuperUsuario2022.',
        'HOST':'127.0.0.1',  # localhost también valdría
        'DATABASE_PORT':'5432'
    }
}'''
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'rsxkoykr',
        'USER': 'rsxkoykr',
        'PASSWORD': 'rhruYV5osl80to7a-Aca7eui-QMZk7Wy',
        'HOST': 'kandula.db.elephantsql.com',
        'DATABASE_PORT': '5432'
    }
}
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'VAD_Journey.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-eu'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'Aplicaciones/FrontEnd/static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/Aplicaciones/FrontEnd/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Aplicaciones/FrontEnd/media')


AUTHENTICATION_BACKENDS = [
    'Aplicaciones.users.backends.CustomEmailAuthBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
    ]

ACCOUNT_FORMS = {'signup': 'Aplicaciones.users.admin.UserCreationForm'}
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'email'

#################################
###  3rd PARTIES AUTH  ##########
#################################
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

#################################
###  EMAIL  #####################
#################################
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_FROM = "vad.journey@gmail.com"
EMAIL_HOST_USER = "vad.journey@gmail.com"
EMAIL_HOST_PASSWORD = "ktzqeajqysjhatap"
EMAIL_USE_TLS = True # necesita autenticacion
EMAIL_PORT = 587

PASSWORD_RESET_TIMEOUT = 86400 # 6 horas

AUTH_USER_MODEL = 'users.Usuario'

#################################
###  RECAPTCHA  #################
#################################
RECAPTCHA_PUBLIC_KEY = '6Lf0owwnAAAAAMdN0o2Am_baoRYEFmVEJd0ZvS0j'
RECAPTCHA_PRIVATE_KEY = '6Lf0owwnAAAAAJ0JSMYdii6Lqn_VKFIOdzl_PytE'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']


#################################
###  PWA  #######################
#################################
PWA_APP_NAME = 'vad_journey'
PWA_APP_DESCRIPTION = "VAD Journey PWA"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/Square150x150Logo.scale-100.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/Square150x150Logo.scale-100.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/img/Square150x150Logo.scale-100.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
















