# Generated by Django 4.0.5 on 2023-10-28 12:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comunidadauto', models.PositiveIntegerField(default='-1')),
                ('comunidadauto', models.CharField(blank=True, max_length=3000, null=True)),
                ('id_provincia', models.PositiveIntegerField(default='-1')),
                ('provincia', models.CharField(blank=True, max_length=3000, null=True)),
                ('id_isla', models.PositiveIntegerField(default='-1')),
                ('isla', models.CharField(blank=True, max_length=3000, null=True)),
                ('dc', models.PositiveIntegerField(default='-1')),
                ('id_municipio', models.PositiveIntegerField(default='-1')),
                ('municipio', models.CharField(blank=True, max_length=3000, null=True)),
                ('direccion', models.CharField(blank=True, max_length=3000, null=True)),
                ('coordenada_x', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('coordenada_y', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'localizaciones',
                'verbose_name_plural': 'localizaciones',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido1', models.CharField(max_length=64)),
                ('apellido2', models.CharField(blank=True, max_length=64, null=True)),
                ('fec_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(max_length=8)),
                ('numero_documento', models.CharField(max_length=32, unique=True)),
                ('num_telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('genero', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, null=True)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=1, default=3.5, max_digits=2, null=True)),
                ('prestigio', models.CharField(blank=True, choices=[('B', 'Bronce'), ('P', 'Plata'), ('Pl', 'Platino'), ('O', 'Oro'), ('D', 'Diamante')], default='B', max_length=2, null=True)),
                ('numero_opiniones', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=3000, null=True)),
                ('imagen', models.ImageField(default='images/users_profile/avatar-mujer.jpg', upload_to='images/users_profile')),
                ('pref_conversacion', models.PositiveIntegerField(default='1')),
                ('pref_musica', models.PositiveIntegerField(default='1')),
                ('pref_mascota', models.PositiveIntegerField(default='1')),
                ('pref_fumar', models.PositiveIntegerField(default='1')),
                ('pref_comida', models.PositiveIntegerField(default='1')),
                ('notif_noticiasofertas', models.PositiveIntegerField(default='3')),
                ('notif_opiniones', models.PositiveIntegerField(default='3')),
                ('notif_reservas', models.PositiveIntegerField(default='3')),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personas',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('C', 'Combustible'), ('E', 'Electrico'), ('H', 'Hibrido')], default='C', max_length=1)),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=12)),
                ('anyo_antiguedad', models.PositiveIntegerField()),
                ('numero_asientos', models.PositiveIntegerField()),
                ('flag_acepta_fumador', models.BooleanField(default=False)),
                ('flag_acepta_mascota', models.BooleanField(default=False)),
                ('matricula', models.CharField(default='0000XXXX', max_length=8)),
                ('imagen_vehiculo', models.ImageField(default='images/vehicles/default-car.jpeg', upload_to='images/vehicles')),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
            ],
            options={
                'verbose_name': 'vehiculos',
                'verbose_name_plural': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=64)),
                ('ciudad_destino', models.CharField(max_length=64)),
                ('fecha_ida', models.DateField(blank=True, null=True)),
                ('numero_asientos_viaje', models.PositiveSmallIntegerField()),
                ('equipaje', models.CharField(choices=[('EP', 'Maleta pequeña'), ('EM', 'Maleta mediana'), ('EG', 'Maleta grande')], default='EM', max_length=2)),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Cancelado')], default=1)),
                ('importe_total_asiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('importe_comision_asiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('importe_conductor_asiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_asientos_libres', models.PositiveIntegerField(default=0)),
                ('hora_ida', models.TimeField()),
                ('fechor_ida', models.DateTimeField()),
                ('fechor_pendiente', models.DateTimeField(blank=True, null=True)),
                ('fechor_realizado', models.DateTimeField(blank=True, null=True)),
                ('fechor_cancelado', models.DateTimeField(blank=True, null=True)),
                ('flg_ida_vuelta', models.BooleanField(default=False)),
                ('distancia_kms', models.DecimalField(decimal_places=1, max_digits=6)),
                ('duracion_min', models.PositiveIntegerField()),
                ('fechor_llegada', models.DateTimeField()),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
                ('id_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.vehiculos')),
            ],
            options={
                'verbose_name': 'viajes',
                'verbose_name_plural': 'viajes',
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Cancelado'), (4, 'Denegado'), (5, 'Error')], default=1)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
            options={
                'verbose_name': 'transferencias',
                'verbose_name_plural': 'transferencias',
            },
        ),
        migrations.CreateModel(
            name='Plazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_conductor', models.BooleanField(default=False)),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Rechazado'), (4, 'Cancelado')], default=1)),
                ('fechor_pendiente', models.DateTimeField(blank=True, null=True)),
                ('fechor_confirmado', models.DateTimeField(blank=True, null=True)),
                ('fechor_rechazado', models.DateTimeField(blank=True, null=True)),
                ('fechor_cancelado', models.DateTimeField(blank=True, null=True)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
            options={
                'verbose_name': 'plazas',
                'verbose_name_plural': 'plazas',
            },
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('categoria_puntuacion', models.PositiveIntegerField(choices=[(1, 'Muy Mal'), (2, 'Mal'), (3, 'Bien'), (4, 'Muy Bien'), (5, 'Excelente')], default=3)),
                ('mensaje_opinion', models.CharField(blank=True, max_length=3000, null=True)),
                ('fechor_opinion', models.DateTimeField(blank=True, null=True)),
                ('flg_leido', models.BooleanField(default=False)),
                ('flg_opinion_respondida', models.BooleanField(default=False)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_opinion_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.opiniones')),
                ('id_persona_publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_publicador', to='FrontEnd.personas')),
                ('id_persona_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_receptor', to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
            options={
                'verbose_name': 'opiniones',
                'verbose_name_plural': 'opiniones',
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Cancelado'), (4, 'Denegado'), (5, 'Error')], default=1)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
            options={
                'verbose_name': 'transferencias',
                'verbose_name_plural': 'transferencias',
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=3000, null=True)),
                ('flg_leido', models.BooleanField(default=False)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona_publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_publicador_m', to='FrontEnd.personas')),
                ('id_persona_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_receptor_m', to='FrontEnd.personas')),
            ],
            options={
                'verbose_name': 'mensajes',
                'verbose_name_plural': 'mensajes',
            },
        ),
    ]
