# Generated by Django 4.0.5 on 2023-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='flg_confirmacion_manual',
            field=models.BooleanField(default=True),
        ),
    ]
