# Generated by Django 4.0.5 on 2023-11-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_viajes_flg_confirmacion_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='flg_confirmacion_manual',
            new_name='flg_confirmacion_auto',
        ),
    ]
