# Generated by Django 4.0.5 on 2024-06-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_rename_flg_confirmacion_manual_viajes_flg_confirmacion_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='importe_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='tipo_descuento',
            field=models.CharField(choices=[('OP', 'Opinion Publicada'), ('O', 'Otros')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='tipo_transferencia',
            field=models.CharField(choices=[('C', 'Cobro'), ('P', 'Pago')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='viajes',
            name='detalles',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Reembolso'), (4, 'Denegado'), (5, 'Error')], default=1),
        ),
        migrations.AlterField(
            model_name='transferencias',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Reembolso'), (4, 'Denegado'), (5, 'Error')], default=1),
        ),
        migrations.CreateModel(
            name='Caparazones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiomas', models.CharField(blank=True, max_length=128, null=True)),
                ('profesion', models.CharField(blank=True, max_length=64, null=True)),
                ('aficiones', models.CharField(blank=True, max_length=256, null=True)),
                ('estilo_musica', models.CharField(blank=True, max_length=64, null=True)),
                ('grupos_musica', models.CharField(blank=True, max_length=256, null=True)),
                ('libros', models.CharField(blank=True, max_length=256, null=True)),
                ('peliculas', models.CharField(blank=True, max_length=256, null=True)),
                ('deportes', models.CharField(blank=True, max_length=64, null=True)),
                ('alimentacion', models.CharField(blank=True, max_length=64, null=True)),
                ('animales', models.CharField(blank=True, max_length=64, null=True)),
                ('fec_created', models.DateTimeField(auto_now_add=True)),
                ('fec_updated', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
            ],
            options={
                'verbose_name': 'caparazones',
                'verbose_name_plural': 'caparazones',
            },
        ),
    ]
