# Generated by Django 4.0.5 on 2024-06-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_transferencias_importe_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniones',
            name='id_opinion_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_opinion_preg', to='FrontEnd.opiniones'),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='id_opinion_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_opinion_resp', to='FrontEnd.opiniones'),
        ),
    ]
