# Generated by Django 5.1.3 on 2024-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_opiniones_id_opinion_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazas',
            name='estado_plaza_viaje',
            field=models.PositiveIntegerField(choices=[(1, 'Sin Estado'), (2, 'Realizado'), (3, 'Finalizado'), (4, 'Problemático')], default=1),
        ),
        migrations.AddField(
            model_name='viajes',
            name='fechor_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Finalizado'), (3, 'Cancelado'), (4, 'Realizado'), (5, 'Problemático')], default=1),
        ),
    ]
