# Generated by Django 5.1.3 on 2025-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_plazas_estado_plaza_viaje_viajes_fechor_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='punto_destino',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viajes',
            name='punto_recogida',
            field=models.CharField(default='', max_length=255),
        ),
    ]
