"""
Django settings for Muvil project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from .db import SQLITE, POSTGRE_MUVIL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'Aplicaciones/FrontEnd/static/js', 'serviceworker.js')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_u7d(jjmsy0n79)@v0d)n#w^odr@_*eenkj4agmn8nq5=ewt2%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps locales
    'Aplicaciones.FrontEnd',
    'Aplicaciones.users',
    # PWA
    'pwa_webpush',
    # Google recaptcha
    'captcha',
    # Import or export to/from file to Django ORM
    'import_export',
    # phone numbers
    'phonenumber_field',
    # social auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ... include the providers you want to enable:
    #'allauth.socialaccount.providers.facebook',
    #'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    #'allauth.socialaccount.providers.microsoft',
    #'allauth.socialaccount.providers.paypal',
    #'allauth.socialaccount.providers.reddit',
    #'allauth.socialaccount.providers.telegram',
    #'allauth.socialaccount.providers.twitter',
]


SOCIALACCOUNT_LOGIN_ON_GET = True

#USE_X_FORWARDED_HOST = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # social auth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'Muvil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

WSGI_APPLICATION = 'Muvil.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = SQLITE
##DATABASES = POSTGRE_MUVIL


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-eu'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'Aplicaciones/FrontEnd/static'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/Aplicaciones/FrontEnd/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


AUTHENTICATION_BACKENDS = [
    'Aplicaciones.users.backends.CustomEmailAuthBackend',
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend'
    ]

ACCOUNT_FORMS = {'signup': 'Aplicaciones.users.admin.UserCreationForm'}

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

#################################
###  3rd PARTIES AUTH  ##########
#################################
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '944380967912-p3te5bu5nct37384av92igc2pdt0nuaf.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}
'''
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
'''

#################################
###  EMAIL  #####################
#################################
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
#EMAIL_FROM = "vad.journey@gmail.com"
#EMAIL_HOST_USER = "vad.journey@gmail.com"
#EMAIL_HOST_PASSWORD = "ktzqeajqysjhatap"
EMAIL_FROM = "muvil.group@gmail.com"
EMAIL_HOST_USER = "muvil.group@gmail.com"
EMAIL_HOST_PASSWORD = "zlwudviqjvmmqktb" # Google Account > Ver en 2 pasos > Crear contraseña de applicaciones
EMAIL_USE_TLS = True # necesita autenticacion
EMAIL_PORT = 587

PASSWORD_RESET_TIMEOUT = 21600 # 6 horas

AUTH_USER_MODEL = 'users.Usuario'

#################################
###  RECAPTCHA  #################
#################################
RECAPTCHA_PUBLIC_KEY = '6Lf0owwnAAAAAMdN0o2Am_baoRYEFmVEJd0ZvS0j'
RECAPTCHA_PRIVATE_KEY = '6Lf0owwnAAAAAJ0JSMYdii6Lqn_VKFIOdzl_PytE'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

#################################
###  PWA  #######################
#################################
PWA_APP_NAME = 'Muvil'
PWA_APP_DESCRIPTION = "Muvil PWA"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/Logo_Nuevo_150x150.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/img/Logo_Nuevo_512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/Logo_Nuevo_150x150.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/img/Logo_Nuevo_512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/img/Logo_Nuevo_150x150.png',
        'sizes': '150x150',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/img/Logo_Nuevo_512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es-eu'
















