# Generated by Django 4.0.5 on 2022-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='numero2',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
