# Generated by Django 4.0.5 on 2022-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_prueba_numero2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=64)),
                ('apellido1', models.CharField(max_length=64)),
                ('apellido2', models.CharField(max_length=64)),
                ('fec_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(max_length=8)),
                ('numero_documento', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=320)),
                ('numero_telefono', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehiculo', models.PositiveIntegerField()),
                ('id_persona', models.PositiveIntegerField()),
                ('tipo_vehiculo', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=12)),
                ('años_antiguedad', models.PositiveIntegerField()),
                ('numero_asientos', models.PositiveIntegerField()),
                ('flag_acepta_fumador', models.BooleanField()),
                ('flag_acepta_mascota', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.PositiveIntegerField()),
                ('id_persona', models.PositiveIntegerField()),
                ('ciudad_origen', models.CharField(max_length=64)),
                ('ciudad_destino', models.CharField(max_length=64)),
                ('flg_ida_vuelta', models.BooleanField()),
                ('fecha_ida', models.DateField()),
                ('fecha_vuelta', models.DateField()),
                ('numero_asientos_viaje', models.PositiveSmallIntegerField()),
                ('flg_solicitado', models.BooleanField()),
                ('flg_reservado', models.BooleanField()),
                ('flg_cancelado', models.BooleanField()),
                ('flg_incidencia', models.BooleanField()),
                ('importe_total_asiento', models.PositiveSmallIntegerField()),
                ('importe_comision_asiento', models.PositiveSmallIntegerField()),
                ('importe_conductor_asiento', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
