# Generated by Django 4.0.5 on 2022-08-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_personas_vehiculos_viajes_delete_prueba'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personas',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='vehiculos',
            table='vehiculos',
        ),
        migrations.AlterModelTable(
            name='viajes',
            table='viajes',
        ),
    ]
