# Generated by Django 4.0.5 on 2022-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_alter_personas_table_alter_vehiculos_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='flag_acepta_fumador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='flag_acepta_mascota',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('C', 'Combustible'), ('E', 'Electrico'), ('H', 'Hibrido')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='flg_cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='flg_ida_vuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='flg_incidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='flg_reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='flg_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='personas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehiculos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='viajes',
            table=None,
        ),
    ]
