# Generated by Django 4.0.5 on 2022-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_personas_genero_alter_vehiculos_flag_acepta_fumador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='importe_comision_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='importe_conductor_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='importe_total_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
