# Generated by Django 4.0.5 on 2022-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_alter_viajes_importe_comision_asiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='importe_comision_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='importe_conductor_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='importe_total_asiento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
