# Generated by Django 4.0.5 on 2022-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_alter_viajes_importe_comision_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='password',
            field=models.CharField(default='<NO_PASSWORD>', max_length=30),
        ),
    ]
