# Generated by Django 4.0.5 on 2022-08-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_personas_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='id_persona',
        ),
    ]
