# Generated by Django 4.0.5 on 2022-08-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_remove_personas_id_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='numero_asientos_libres',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
