# Generated by Django 4.0.5 on 2022-08-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0010_vehiculos_numero_asientos_libres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='id_vehiculo',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='id_viaje',
        ),
    ]
