# Generated by Django 4.0.5 on 2022-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0011_remove_vehiculos_id_vehiculo_remove_viajes_id_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='numero_asientos_libres',
        ),
        migrations.AddField(
            model_name='viajes',
            name='numero_asientos_libres',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
