# Generated by Django 4.0.5 on 2022-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0012_remove_vehiculos_numero_asientos_libres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='hora_ida',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='hora_vuelta',
            field=models.TimeField(default='00:00'),
        ),
    ]
