# Generated by Django 4.0.5 on 2022-08-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0013_viajes_hora_ida_viajes_hora_vuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas'),
        ),
    ]
