# Generated by Django 4.0.5 on 2022-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0014_alter_vehiculos_id_persona_alter_viajes_id_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='des_prestigio',
            field=models.CharField(choices=[('B', 'Bronce'), ('P', 'Plata'), ('X', 'Platino'), ('O', 'Oro'), ('D', 'Diamante')], default='Pl', max_length=2),
        ),
        migrations.AddField(
            model_name='personas',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
    ]
