# Generated by Django 4.0.5 on 2022-08-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0015_personas_des_prestigio_personas_puntuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='id_persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas'),
        ),
    ]
