# Generated by Django 4.0.5 on 2022-08-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0016_remove_vehiculos_id_persona_vehiculos_id_persona_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='id_persona_id',
            new_name='id_persona',
        ),
    ]
