# Generated by Django 4.0.5 on 2022-08-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0017_rename_id_persona_id_vehiculos_id_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='des_prestigio',
            new_name='prestigio',
        ),
    ]
