# Generated by Django 4.0.5 on 2022-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0018_rename_des_prestigio_personas_prestigio'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='numero_opiniones',
            field=models.PositiveIntegerField(default='17'),
        ),
    ]
