# Generated by Django 4.0.5 on 2022-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0019_personas_numero_opiniones'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='ruta_foto',
            field=models.CharField(default='img/avatar-mujer.jpg', max_length=32),
        ),
        migrations.AlterField(
            model_name='personas',
            name='prestigio',
            field=models.CharField(choices=[('B', 'Bronce'), ('P', 'Plata'), ('Pl', 'Platino'), ('O', 'Oro'), ('D', 'Diamante')], default='Pl', max_length=2),
        ),
    ]
