# Generated by Django 4.0.5 on 2022-08-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0020_personas_ruta_foto_alter_personas_prestigio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_opiniones',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='prestigio',
            field=models.CharField(choices=[('B', 'Bronce'), ('P', 'Plata'), ('Pl', 'Platino'), ('O', 'Oro'), ('D', 'Diamante')], default='B', max_length=2),
        ),
    ]
