# Generated by Django 4.0.5 on 2022-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0021_alter_personas_numero_opiniones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='ruta_foto2',
            field=models.FileField(null=True, upload_to='static/img/personas/'),
        ),
    ]
