# Generated by Django 4.0.5 on 2022-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0022_personas_ruta_foto2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='ruta_foto2',
            field=models.FileField(null=True, upload_to='img/personas/'),
        ),
    ]
