# Generated by Django 4.0.5 on 2022-08-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0023_alter_personas_ruta_foto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='ruta_foto2',
        ),
    ]
