# Generated by Django 4.0.4 on 2023-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0024_remove_personas_ruta_foto2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fec_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_opiniones',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_telefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='password',
            field=models.CharField(blank=True, default='<NO_PASSWORD>', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='prestigio',
            field=models.CharField(blank=True, choices=[('B', 'Bronce'), ('P', 'Plata'), ('Pl', 'Platino'), ('O', 'Oro'), ('D', 'Diamante')], default='B', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.5, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='ruta_foto',
            field=models.CharField(blank=True, default='img/avatar-mujer.jpg', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
