# Generated by Django 4.0.4 on 2023-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0025_alter_personas_email_alter_personas_fec_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
