# Generated by Django 4.0.4 on 2023-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0026_personas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='apellido2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.CharField(default='vad@vad.com', max_length=320),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.CharField(default='123ABC', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_telefono',
            field=models.PositiveIntegerField(default=1234556),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='password',
            field=models.CharField(default='<NO_PASSWORD>', max_length=30),
        ),
        migrations.AlterField(
            model_name='personas',
            name='tipo_documento',
            field=models.CharField(default='NIF', max_length=8),
            preserve_default=False,
        ),
    ]
