# Generated by Django 4.0.4 on 2023-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0027_alter_personas_apellido2_alter_personas_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
