# Generated by Django 4.0.4 on 2023-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0028_personas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/users_profile'),
        ),
    ]
