# Generated by Django 4.0.4 on 2023-02-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0029_alter_personas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='fechor_ida',
            field=models.DateTimeField(default='1990-01-01 00:00'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='fechor_vuelta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='fecha_vuelta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='hora_vuelta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='id_persona',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas'),
        ),
    ]
