# Generated by Django 4.0.4 on 2023-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0030_viajes_fechor_ida_viajes_fechor_vuelta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_telefono',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
