# Generated by Django 4.0.5 on 2023-02-14 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0031_alter_personas_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(blank=True, default='images/users_profile/avatar-mujer.jpg', null=True, upload_to='images/users_profile'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
