# Generated by Django 4.0.5 on 2023-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0032_alter_personas_imagen_alter_personas_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imagen',
            field=models.ImageField(default='images/users_profile/avatar-mujer.jpg', upload_to='images/users_profile'),
        ),
    ]
