# Generated by Django 4.0.5 on 2023-02-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0033_alter_personas_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='años_antiguedad',
            new_name='año_antiguedad',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='matricula',
            field=models.CharField(default='0000XXXX', max_length=8),
        ),
    ]
