# Generated by Django 4.0.5 on 2023-02-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0034_rename_años_antiguedad_vehiculos_año_antiguedad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='año_antiguedad',
            new_name='anyo_antiguedad',
        ),
    ]
