# Generated by Django 4.0.5 on 2023-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0035_rename_año_antiguedad_vehiculos_anyo_antiguedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen_vehiculo',
            field=models.ImageField(default='images/vehicles/default-car.jpeg', upload_to='images/vehicles'),
        ),
    ]
