# Generated by Django 4.0.5 on 2023-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0036_vehiculos_imagen_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='pref_comida',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='personas',
            name='pref_conversacion',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='personas',
            name='pref_fumar',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='personas',
            name='pref_mascota',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='personas',
            name='pref_musica',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
