# Generated by Django 4.0.5 on 2023-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0037_personas_pref_comida_personas_pref_conversacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='notif_noticiasofertas',
            field=models.PositiveIntegerField(default='3'),
        ),
        migrations.AddField(
            model_name='personas',
            name='notif_opiniones',
            field=models.PositiveIntegerField(default='3'),
        ),
        migrations.AddField(
            model_name='personas',
            name='notif_reservas',
            field=models.PositiveIntegerField(default='3'),
        ),
    ]
