# Generated by Django 4.0.5 on 2023-02-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0038_personas_notif_noticiasofertas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.vehiculos'),
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_destino', to='FrontEnd.personas')),
                ('id_persona_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_origen', to='FrontEnd.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('categoria_puntuacion', models.PositiveIntegerField(choices=[(1, 'Muy Mal'), (2, 'Mal'), (3, 'Correcto'), (4, 'Muy Bien'), (5, 'Excelente')], default=3)),
                ('mensaje_opinion', models.CharField(blank=True, max_length=3000, null=True)),
                ('flg_respuesta', models.BooleanField(default=False)),
                ('mensaje_respuesta', models.CharField(blank=True, max_length=3000, null=True)),
                ('id_persona_publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_publicador', to='FrontEnd.personas')),
                ('id_persona_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_receptor', to='FrontEnd.personas')),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.viajes')),
            ],
        ),
    ]
