# Generated by Django 4.0.5 on 2023-02-23 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0039_viajes_id_vehiculo_transferencias_reservas_opiniones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fec_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='fec_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
